import re
from collections import Counter

# --- 1. The Methodology-Aware Parser ---
def extract_user_dialogue(transcript: str) -> list:
    """
    Parses a raw UX transcript and extracts ONLY the user's dialogue.
    Ignores moderator questions to prevent false positives in intent detection.
    """
    user_quotes = []
    lines = transcript.split('\n')
    
    for line in lines:
        # Looks for tags like [User], User:, or USER:
        if re.match(r"^\[?User\]?:?", line.strip(), re.IGNORECASE):
            # Strip the tag and keep just the text
            clean_text = re.sub(r"^\[?User\]?:?\s*", "", line.strip(), flags=re.IGNORECASE)
            if clean_text:
                user_quotes.append(clean_text)
                
    return user_quotes

# --- 2. The Automated UX Report Generator ---
def generate_markdown_report(analysis_results: list, top_themes: str = "") -> str:
    """
    Converts a list of JSON analysis results into a formatted Markdown report.
    """
    if not analysis_results:
        return "No user dialogue found to analyze."

    total_quotes = len(analysis_results)
    
    # Tally up the intents and issues
    intents = Counter([res['analysis']['primary_intent'] for res in analysis_results])
    issues = Counter([res['analysis']['perceived_issue'] for res in analysis_results])

    # Check if 'true_emotion' exists (from the sarcasm-proof model) or fallback to 'user_emotion'
    if 'true_emotion' in analysis_results[0]['analysis']:
        emotions = Counter([res['analysis']['true_emotion'] for res in analysis_results])
    else:
        emotions = Counter([res['analysis'].get('user_emotion', 'Neutral') for res in analysis_results])

    top_intent = intents.most_common(1)[0]
    top_issue = issues.most_common(1)[0]
    top_emotion = emotions.most_common(1)[0]

    # Construct the Markdown string
    report = f"""# 📊 Usability Analysis Report

## Executive Summary
* **Utterances Analyzed:** {total_quotes}
* **Primary User Goal:** `{top_intent[0]}` ({top_intent[1]} mentions)
* **Top Usability Blocker:** `{top_issue[0]}` ({top_issue[1]} mentions)
* **Dominant Emotion:** {top_emotion[0]}

## Issue Breakdown
"""
    for issue, count in issues.most_common():
        if issue != "No Issue":
            report += f"- **{issue}**: {count} occurrences\n"
            
    if top_themes:
        report += f"\n## Semantic Clusters Discovered\n{top_themes}\n"
            
    report += "\n*Report auto-generated by the GSoC '26 Intent & Semantic Analysis NLP Module.*"
    return report